services:

  backend:
    build: ./docker
    ports:
      - '80:80'
    volumes:
      - ./src/:/var/www/html/
    networks:
      - acessorias-network
    depends_on:
      - db

  db:
    image: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: acessorias
      MYSQL_ROOT_PASSWORD: 4c3ss0r14sr00t
      MYSQL_USER: acessorias
      MYSQL_PASSWORD: 4c3ss0r14s
    volumes:
      - db-data:/var/lib/mysql
      - ./db/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - acessorias-network

networks:
  acessorias-network:
    driver: bridge

volumes:
  db-data:
    driver: local
